### ISSUE TITLE
Video Link Broken - Comfort Respirator

### ISSUE THREAD

**Issue by BelindaRandolph** [nasa-jpl/COVID-19-respirators#4]
I was hoping to watch the video below.

Current design: The JPL designer of the 3D printable COVID-19 Comfort Respirator describes the preferred design. https://youtu.be/vaxoGQcy00

**Comment by tomsoderstrom** [comment]
Thanks for letting us know.  We're fixing it now.

**Comment by ericdcontreras** [comment]
Fixed!! and added a new video. Will update others soon
